name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar el código
        uses: actions/checkout@v4

      - name: 🔧 Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🧪 Correr tests con coverage
        run: npm run test -- --coverage

      - name: 📊 Subir los resultados a Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-actions
      
      - name: 📋 Subir los detalles de los test a Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1